{% set name = "polyfempy" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://github.com/polyfem/polyfem-python/archive/{{ version }}.tar.gz
  sha256: 5cc33ca5f6eaadbc0baa6cbd89c112807a01b1a1502736188236bf84fdbcbe5a

build:
  number: 0
  skip: True  # [py<31]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - libblas
    - libcblas
    - numpy
    - suitesparse
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - suitesparse

test:
  imports:
    - polyfempy

about:
  home: https://polyfem.github.io/

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

  summary: 'Easy-to-use powerfull finite element library based on Polyfem'

  description: 'Easy-to-use powerfull finite element library based on Polyfem'
  doc_url: https://polyfem.github.io/
  dev_url: https://github.com/polyfem/polyfem-python

extra:
  recipe-maintainers:
    - teseoch
