{% set name = "polyfempy" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://github.com/polyfem/polyfem-python/archive/{{ version }}.tar.gz
  sha256: 9f2363c2f6356ca263c5700cc8687fefcef4117162808c3f17680e139db7d44c

build:
  number: 0
  skip: True  # [py<31]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - cmake
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy >=1.9.1

test:
  imports:
    - polyfempy

about:
  home: https://polyfem.github.io/

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

  summary: 'Easy-to-use powerfull finite element library based on Polyfem'

  description: 'Easy-to-use powerfull finite element library based on Polyfem'
  doc_url: https://polyfem.github.io/
  dev_url: https://github.com/polyfem/polyfem-python

extra:
  recipe-maintainers:
    - teseoch
