{% set name = "polyfempy" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://github.com/polyfem/polyfem-python/archive/{{ version }}.tar.gz
  sha256: b3e5cea6672a657fcb2a7bcf40e5a7a41f4f8735f9b5179e7ffa44ec496b4030

build:
  number: 1
  # skip: True  # [py<31]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - cmake
  host:
    - python
    - pip
    - suitesparse
    - setuptools
  run:
    - python
    - numpy >=1.9.1

test:
  imports:
    - polyfempy

about:
  home: https://polyfem.github.io/

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

  summary: 'Easy-to-use powerfull finite element library based on Polyfem'

  description: 'Easy-to-use powerfull finite element library based on Polyfem'
  doc_url: https://polyfem.github.io/
  dev_url: https://github.com/polyfem/polyfem-python

extra:
  recipe-maintainers:
    - teseoch
